/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author estef
 */
   
import java.awt.Frame;           // Necesario para el constructor del JDialog (parent)
import java.awt.event.ActionEvent; // Para ActionListener
import java.awt.event.ActionListener; // Para ActionListener
import java.awt.event.WindowAdapter;  // Para gestionar el cierre de ventana
import java.awt.event.WindowEvent;   // Para gestionar el cierre de ventana
import javax.swing.JOptionPane;


public class NombrePersonaje extends javax.swing.JDialog {
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(NombrePersonaje.class.getName());
    
    // --- VARIABLES DE LA CLASE ---
    private String nombreIngresado = null; // Almacena el nombre validado
    private boolean cancelado = false;     // Indica si el usuario canceló o cerró el diálogo
    

    /**
     * Constructor
     */
    
    public NombrePersonaje(java.awt.Frame parent, boolean modal) {
        
        super(parent, modal);
        initComponents(); // Este método inicializa todos los componentes de la interfaz.
        setLocationRelativeTo(null); // Centra el diálogo en la pantalla.

        // Añade el WindowListener para detectar si el usuario cierra el diálogo con la 'X'.
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                cancelado = true; // Si se cierra con la 'X', se considera una cancelación.
                dispose();        // Libera los recursos del JDialog.
            }
        });

        // Asociación de los ActionListeners a los botones Aceptar y Cancelar
        
        if (btnAceptar != null) { 
            btnAceptar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnAceptarActionPerformed(e);
                }
            });
        }
        if (btnCancelar != null) { 
            btnCancelar.addActionListener(new ActionListener() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    btnCancelarActionPerformed(e);
                }
            });
        }
        
    } 
    
    public String getNombreIngresado() {
        return nombreIngresado;
    }

    public boolean isCancelado() {
        return cancelado;
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNombreJugador = new javax.swing.JTextField();
        btnCancelar = new javax.swing.JButton();
        btnAceptar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Ingresar Nombre");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNombreJugador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreJugadorActionPerformed(evt);
            }
        });
        getContentPane().add(txtNombreJugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 250, 410, 90));

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 400, -1, -1));

        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, -1, -1));

        jLabel2.setFont(new java.awt.Font("Monospaced", 3, 36)); // NOI18N
        jLabel2.setText("Introduce tu nombre de héroe:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/Fondo - ventana 2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 740, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        nombreIngresado = txtNombreJugador.getText().trim(); // Obtiene el texto y quita espacios
    if (nombreIngresado.isEmpty()) {
        
        // Muestra un mensaje si el nombre está vacío
        javax.swing.JOptionPane.showMessageDialog(this, "Por favor, introduce un nombre.", "Error", javax.swing.JOptionPane.WARNING_MESSAGE);
        nombreIngresado = null; // Resetea el nombre si está vacío
    } else {
        this.dispose(); 
    }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cancelado = true; // Marca que el diálogo fue cancelado
        this.dispose(); // Cierra el diálogo
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtNombreJugadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreJugadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreJugadorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                NombrePersonaje dialog = new NombrePersonaje(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtNombreJugador;
    // End of variables declaration//GEN-END:variables
}
